const famousPeople = [
  "Jesus",
  "Adolf Hitler",
  "Marilyn Monroe",
  "Donald Trump",
  "Albert Enstein",
  "Cleopatra",
  "Michael Jackson",
  "Charlie Chaplin",
  "Abraham Lincoln",
  "Julius Ceasar",
  "Joan of Arc",
  "John Lennon",
  "Mother Theresa",
  "John F. Kennedy",
  "Gandhi",
];

const objects = [
  "Car",
  "Giraffe",
  "Sydney Opera House",
  "Eiffle Tower",
  "Sofa",
  "Elephant",
  "Tree",
  "Train",
  "Bus",
  "Bike",
  "Window",
  "Door",
  "House",
  "Mug",
  "Curtains",
  "Piece of Cake",
  "Carrot",
  "Ball",
  "Baseball Cap",
  "Hipster",
  "Nostrel",
  "Battery",
  "Smart Watch",
];

module.exports = { objects, famousPeople };
